version: "3.8"
services:
  mongodb:
    container_name: "${PROJECT_NAME}_mongo"
    image: mongo:latest
    volumes:
      - ./backend/data:/data
    ports:
      - "27017:27017"
    init: true

  backend:
    container_name: "${PROJECT_NAME}_backend"
    build: ./backend
    env_file:
      - ./backend/.env.sample
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    init: true      

  frontend:
    container_name: "${PROJECT_NAME}_frontend"
    build: ./frontend
    env_file:
      - ./frontend/.env.sample
    ports:
      - "5173:5173"
    init: true      

  redis:
    container_name: "${PROJECT_NAME}_redis"
    restart: unless-stopped
    image: redis:7.0.5-alpine 
    expose:
        - 6379
    depends_on:
      - mongodb
    init: true

volumes:
  data:
